name: Deploy to VPS (Docker Run)

on:
  push:
    branches:
      - main  # Ветка main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass  # Установка sshpass

      - name: Copy files to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            ./ root@${{ secrets.VPS_HOST }}:/root/app/

      - name: Rebuild & Run Docker
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            root@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/app
            docker stop pocketer-bot || true
            docker rm pocketer-bot || true
            docker build -t pocketer-bot .
            docker run -d --name pocketer-bot --restart always pocketer-bot
          EOF
