name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy files to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" ./ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/app

      - name: Deploy on VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/app

            # Остановим старый контейнер, если он был
            docker stop app || true && docker rm app || true

            # Соберем и запустим новый контейнер
            docker build -t my-app .

            docker run -d --name app \
              -e TOKEN=${{ secrets.TOKEN }} \
              -e CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} \
              -e AUTH_SERVER_URL=${{ secrets.AUTH_SERVER_URL }} \
              -p 80:80 my-app
          EOF
